Developer Guide Security Extension
industrial-edge/Developer-Guide-Hands-on-App pull request #13
Opened 2022-07-26 07:14 UTC by SiHaoShen

- Updated all the open source software (Grafana, InfluxDB, NodeRed)
- Changed NodeRed flows due to software update
- Add additional security aspect in docker-compose.yml: Linux capabilities, read-only file system, non-root user, container initialization

2022-08-01 15:23 UTC, EndyCZ requested changes

2022-08-01 15:23 UTC, EndyCZ commented on src/solution/my_edge_app/docker-compose.yml
> +    image: init-db:v0.0.1               # Docker Init Container to Setup the Main InfluxDB v2.2 Container
Please add build statement with a path https://docs.docker.com/compose/compose-file/compose-file-v2/#build 
the goal is that user of the guide can just directly run docker-compose up -d commad after runnign the  [mosquite docker copose file](src/solution/mqtt_broker_mosquitto/docker-compose.yml)

2022-08-01 15:23 UTC, EndyCZ commented on src/solution/my_edge_app/docker-compose_Edge.yml
> +    mem_limit: 100m
Please add build statement with a path https://docs.docker.com/compose/compose-file/compose-file-v2/#build 
the goal is that user of the guide can just directly run docker-compose up -d commad after runnign the  [mosquite docker copose file](src/solution/mqtt_broker_mosquitto/docker-compose.yml)

2022-08-01 15:23 UTC, EndyCZ commented on src/solution/my_edge_app/influxdb/init_influxdb.sh
> +
Add comment that in this file we would load secrets from various Secrement management sources and use them to confugre the influx db database.

2022-08-01 15:36 UTC, EndyCZ requested changes
I did not found any folder src/solution/tracee which you describes.

2022-08-04 11:54 UTC, EndyCZ requested changes
Please also remove all the $http_proxy and $https_proxy. I think they are not needed anymore from the docker-compose files

2022-08-04 13:39 UTC, SiHaoShen commented
# Feedback from Review of 08.01
I removed all the $http_proxy and $https_proxys variable. Also I added build statement in **docker-compose.yml**, but not in **docker-compose_Edge.yml**. Since build statement is not supported in edge app publisher

2022-09-27 07:57 UTC, EndyCZ commented
Cannot import into IEAP image with enviroment variable. https://github.com/SiHaoShen/Developer-Guide-Hands-on-App/blob/main/src/solution/HandsOn_1/my_edge_app/docker-compose_Edge.yml#L29

2022-10-03 14:44 UTC, EndyCZ approved these changes
Merging now into dev branch to have it availalbe in organization repository. Could not merge because of Software clearing and some small details to adjust.

2022-10-03 14:45 UTC, merged